"""Connection Type for socials

Revision ID: 09d2ee58aee0
Revises: 75835e25b777
Create Date: 2026-04-24 13:16:11.094079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09d2ee58aee0'
down_revision: Union[str, Sequence[str], None] = '75835e25b777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('connection_type', sa.Enum('friend', 'trainership', name='connectiontype'), nullable=True))
    op.drop_column('connections', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('type', postgresql.ENUM('friend', 'trainership', name='connectiontype'), autoincrement=False, nullable=True))
    op.drop_column('connections', 'connection_type')
    # ### end Alembic commands ###
