"""day of week in workout session

Revision ID: 186ec409e823
Revises: 1fe6f314f512
Create Date: 2026-04-13 20:07:38.947206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186ec409e823'
down_revision: Union[str, Sequence[str], None] = '1fe6f314f512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meals_serving_unit_id_fkey', 'meals', type_='foreignkey')
    op.drop_table('meal_plan_items')
    op.drop_table('serving_units')
    op.drop_table('meal_plans')
    op.drop_table('meals')
    op.add_column('workouts_workout_plans', sa.Column('day_of_week', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts_workout_plans', 'day_of_week')
    op.create_table('meals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', 'drink', 'dessert', 'other', name='mealcategory'), autoincrement=False, nullable=False),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('serving_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('serving_unit_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('meals_created_by_fkey')),
    sa.ForeignKeyConstraint(['serving_unit_id'], ['serving_units.id'], name=op.f('meals_serving_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meals_pkey'))
    )
    op.create_index(op.f('ix_meals_name_is_custom'), 'meals', ['name', 'is_custom'], unique=False)
    op.create_index(op.f('ix_meals_name'), 'meals', ['name'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meal_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_plans_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_meal_plans_user_id_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.create_table('meal_plan_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_type', postgresql.ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'evening_snack', name='mealtype'), autoincrement=False, nullable=False),
    sa.Column('servings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('meal_plan_items_meal_id_fkey')),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('meal_plan_items_meal_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_plan_items_pkey'))
    )
    op.create_index(op.f('ix_meal_plan_items_plan_id_type'), 'meal_plan_items', ['meal_plan_id', 'meal_type'], unique=False)
    # ### end Alembic commands ###
