"""add meal plan tables and constraints

Revision ID: 1a4d6f8c9b20
Revises: 15cdf8090f93
Create Date: 2026-04-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1a4d6f8c9b20"
down_revision: Union[str, Sequence[str], None] = "15cdf8090f93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    mealcategory_enum = postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='mealcategory', create_type=False)
    mealtype_enum = postgresql.ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'evening_snack', name='mealtype', create_type=False)
    op.create_table('serving_units',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('meals',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', mealcategory_enum, nullable=False),
        sa.Column('calories', sa.Integer(), nullable=False),
        sa.Column('protein_grams', sa.Float(), nullable=True),
        sa.Column('carbs_grams', sa.Float(), nullable=True),
        sa.Column('fat_grams', sa.Float(), nullable=True),
        sa.Column('fiber_grams', sa.Float(), nullable=True),
        sa.Column('serving_size', sa.String(length=100), nullable=True),
        sa.Column('image_url', sa.String(length=512), nullable=True),
        sa.Column('is_custom', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('serving_unit_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['serving_unit_id'], ['serving_units.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meals_name_is_custom', 'meals', ['name', 'is_custom'], unique=False)
    op.create_index(op.f('ix_meals_name'), 'meals', ['name'], unique=False)

    # Create meal_plans table
    op.create_table('meal_plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('target_calories', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date', name='uq_meal_plans_user_id_date')
    )
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)

    # Create meal_plan_items table
    op.create_table('meal_plan_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('meal_plan_id', sa.UUID(), nullable=False),
        sa.Column('meal_id', sa.UUID(), nullable=False),
        sa.Column('meal_type', mealtype_enum, nullable=False),
        sa.Column('servings', sa.Float(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
        sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_plan_items_plan_id_type', 'meal_plan_items', ['meal_plan_id', 'meal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_plan_items_plan_id_type', table_name='meal_plan_items')
    op.drop_table('meal_plan_items')

    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.drop_table('meal_plans')

    op.drop_index(op.f('ix_meals_name'), table_name='meals')
    op.drop_index('ix_meals_name_is_custom', table_name='meals')
    op.drop_table('meals')

    op.drop_table('serving_units')

    postgresql.ENUM(name='mealtype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='mealcategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
