"""claude revisions

Revision ID: 1e291aa10ac7
Revises: f813e9a470bc
Create Date: 2026-04-15 15:12:31.700666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e291aa10ac7'
down_revision: Union[str, Sequence[str], None] = 'f813e9a470bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_connections_pair', 'connections', ['requester_id', 'addressee_id'])
    op.add_column('conversation_participants', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('conversations', sa.Column('creator_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'users', ['creator_id'], ['id'])
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'height',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('workout_plans', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.alter_column('workout_plans', 'difficulty',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               existing_nullable=True)
    op.create_foreign_key(None, 'workout_plans', 'users', ['assigned_to'], ['id'])
    op.drop_column('workout_plans', 'image_url')
    op.drop_column('workout_plans', 'is_preset')
    op.drop_column('workout_plans', 'is_equipment_needed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('is_equipment_needed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workout_plans', sa.Column('is_preset', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workout_plans', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.alter_column('workout_plans', 'difficulty',
               existing_type=sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('workout_plans', 'assigned_to')
    op.alter_column('user_profiles', 'height',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'reply_to_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'creator_id')
    op.drop_column('conversations', 'name')
    op.drop_column('conversation_participants', 'is_active')
    op.drop_constraint('uq_connections_pair', 'connections', type_='unique')
    # ### end Alembic commands ###
