"""assigned_to attribute in workout plan table

Revision ID: 1fe6f314f512
Revises: 7b004c282190
Create Date: 2026-04-13 15:14:28.924132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe6f314f512'
down_revision: Union[str, Sequence[str], None] = '7b004c282190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workout_plan_workouts')
    op.drop_table('workout_plan_tags')
    op.drop_table('tags')
    op.add_column('workout_plans', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workout_plans', 'users', ['assigned_to'], ['id'])
    op.drop_column('workout_plans', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.drop_column('workout_plans', 'assigned_to')
    op.create_table('tags',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('name', name=op.f('tags_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('workout_plan_tags',
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plan_tags_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('workout_plan_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'tag_id', name=op.f('workout_plan_tags_pkey'))
    )
    op.create_table('workout_plan_workouts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plan_workouts_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('workout_plan_workouts_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_plan_workouts_pkey'))
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('workout_exercises_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('workout_exercises_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_exercises_pkey'))
    )
    # ### end Alembic commands ###
