"""user trainer info + enum for connection type

Revision ID: 22630b7a2cf4
Revises: d99c70948d8c
Create Date: 2026-04-23 22:09:05.718293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22630b7a2cf4'
down_revision: Union[str, Sequence[str], None] = 'd99c70948d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
