"""Add template_name to meal_plans

Revision ID: 2f8997d09f37
Revises: a63a1f92f371
Create Date: 2026-04-17 01:04:52.303325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8997d09f37'
down_revision: Union[str, Sequence[str], None] = 'a63a1f92f371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_connections_pair', 'connections', ['requester_id', 'addressee_id'])
    op.add_column('conversation_participants', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('conversations', sa.Column('creator_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'users', ['creator_id'], ['id'])
    op.add_column('meal_plans', sa.Column('template_name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.create_index('ix_meal_plans_template_name', 'meal_plans', ['template_name'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'height',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.execute("UPDATE workout_plans SET difficulty = lower(difficulty)")
    op.alter_column('workout_plans', 'difficulty',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               existing_nullable=True,
               postgresql_using='difficulty::text::difficultylevel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_plans', 'difficulty',
               existing_type=sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'height',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'reply_to_id')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index('ix_meal_plans_template_name', table_name='meal_plans')
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.drop_column('meal_plans', 'template_name')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'creator_id')
    op.drop_column('conversations', 'name')
    op.drop_column('conversation_participants', 'is_active')
    op.drop_constraint('uq_connections_pair', 'connections', type_='unique')
    # ### end Alembic commands ###
