"""trainer info

Revision ID: 3c3eeca2833c
Revises: 62a10597fab9
Create Date: 2026-04-22 00:21:06.063907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3eeca2833c'
down_revision: Union[str, Sequence[str], None] = '62a10597fab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expertise', sa.String(), nullable=True),
    sa.Column('rate_per_week', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_info')
    # ### end Alembic commands ###
