"""seed_meals_table

Revision ID: 422293052c66
Revises: a63a1f92f371
Create Date: 2026-04-18 19:18:19.159348

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '422293052c66'
down_revision: Union[str, Sequence[str], None] = 'a63a1f92f371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    meals_table = sa.table(
        "meals",
        sa.column("id", sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("category", sa.String),
        sa.column("calories", sa.Integer),
        sa.column("protein_grams", sa.Float),
        sa.column("carbs_grams", sa.Float),
        sa.column("fat_grams", sa.Float),
        sa.column("fiber_grams", sa.Float),
        sa.column("serving_size", sa.String),
        sa.column("is_custom", sa.Boolean),
        sa.column("created_at", sa.DateTime),
    )

    op.bulk_insert(
        meals_table,
        [
            {
                "id": uuid.uuid4(), "name": "Apple", "description": "A crisp, sweet fruit.", "category": "snack",
                "calories": 95, "protein_grams": 0.5, "carbs_grams": 25, "fat_grams": 0.3, "fiber_grams": 4.4,
                "serving_size": "1 medium", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Chicken Breast (Grilled)", "description": "Lean source of protein.", "category": "lunch",
                "calories": 165, "protein_grams": 31, "carbs_grams": 0, "fat_grams": 3.6, "fiber_grams": 0,
                "serving_size": "100g", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Oats (Rolled)", "description": "Whole grain cereal.", "category": "breakfast",
                "calories": 150, "protein_grams": 5, "carbs_grams": 27, "fat_grams": 2.5, "fiber_grams": 4,
                "serving_size": "1/2 cup dry", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Brown Rice", "description": "Whole grain rice.", "category": "lunch",
                "calories": 215, "protein_grams": 5, "carbs_grams": 45, "fat_grams": 1.8, "fiber_grams": 3.5,
                "serving_size": "1 cup cooked", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Salmon (Baked)", "description": "Rich in omega-3 fatty acids.", "category": "dinner",
                "calories": 206, "protein_grams": 22, "carbs_grams": 0, "fat_grams": 12, "fiber_grams": 0,
                "serving_size": "100g", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Broccoli (Steamed)", "description": "Nutrient-rich green vegetable.", "category": "lunch",
                "calories": 55, "protein_grams": 3.7, "carbs_grams": 11.2, "fat_grams": 0.6, "fiber_grams": 5.1,
                "serving_size": "1 cup", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Almonds", "description": "Healthy nuts for snacking.", "category": "snack",
                "calories": 164, "protein_grams": 6, "carbs_grams": 6, "fat_grams": 14, "fiber_grams": 3.5,
                "serving_size": "1/4 cup", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Greek Yogurt (Plain, Non-fat)", "description": "High-protein dairy product.", "category": "breakfast",
                "calories": 100, "protein_grams": 17, "carbs_grams": 6, "fat_grams": 0, "fiber_grams": 0,
                "serving_size": "1 cup", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Banana", "description": "Potassium-rich fruit.", "category": "snack",
                "calories": 105, "protein_grams": 1.3, "carbs_grams": 27, "fat_grams": 0.4, "fiber_grams": 3.1,
                "serving_size": "1 medium", "is_custom": False
            },
            {
                "id": uuid.uuid4(), "name": "Egg (Large, Boiled)", "description": "A versatile source of protein.", "category": "breakfast",
                "calories": 78, "protein_grams": 6, "carbs_grams": 0.6, "fat_grams": 5, "fiber_grams": 0,
                "serving_size": "1 large", "is_custom": False
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM meals WHERE is_custom = false")
    # ### end Alembic commands ###
