"""fix trainer info

Revision ID: 5fe6beeaa8a4
Revises: 3c3eeca2833c
Create Date: 2026-04-22 00:35:59.727675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe6beeaa8a4'
down_revision: Union[str, Sequence[str], None] = '3c3eeca2833c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_info', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'trainer_info', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainer_info', type_='unique')
    op.drop_column('trainer_info', 'name')
    # ### end Alembic commands ###
