"""user_onboarding

Revision ID: 63dfdd844ec4
Revises: e10327c87ca3
Create Date: 2026-05-08 22:56:13.603565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63dfdd844ec4'
down_revision: Union[str, Sequence[str], None] = 'e10327c87ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plans_user_date_unique'), table_name='meal_plans', postgresql_where='((is_template = false) AND (date IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meal_plans_user_date_unique'), 'meal_plans', ['user_id', 'date'], unique=True, postgresql_where='((is_template = false) AND (date IS NOT NULL))')
    # ### end Alembic commands ###
