"""default active value to false

Revision ID: 74e10df74ea2
Revises: f813e9a470bc
Create Date: 2026-04-18 01:54:10.756961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e10df74ea2'
down_revision: Union[str, Sequence[str], None] = 'f813e9a470bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_plans_users')
    op.drop_constraint(op.f('uq_connections_pair'), 'connections', type_='unique')
    op.drop_column('conversation_participants', 'is_active')
    op.drop_constraint(op.f('conversations_creator_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'creator_id')
    op.drop_column('conversations', 'name')
    op.drop_index(op.f('ix_meal_plans_template_name'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.drop_column('meal_plans', 'template_name')
    op.drop_constraint(op.f('messages_reply_to_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'reply_to_id')
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'onboarding_completed')
    op.add_column('workout_plans', sa.Column('is_trainer_provided', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workout_plans', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.alter_column('workout_plans', 'difficulty',
               existing_type=postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'workout_plans', 'users', ['assigned_to'], ['id'])
    op.drop_column('workout_plans', 'image_url')
    op.drop_column('workout_plans', 'is_preset')
    op.drop_column('workout_plans', 'is_equipment_needed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('is_equipment_needed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workout_plans', sa.Column('is_preset', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workout_plans', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.alter_column('workout_plans', 'difficulty',
               existing_type=sa.String(),
               type_=postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficultylevel'),
               existing_nullable=True)
    op.drop_column('workout_plans', 'assigned_to')
    op.drop_column('workout_plans', 'is_trainer_provided')
    op.add_column('user_profiles', sa.Column('onboarding_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('user_profiles', 'height',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_reply_to_id_fkey'), 'messages', 'messages', ['reply_to_id'], ['id'])
    op.add_column('meal_plans', sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_template_name'), 'meal_plans', ['template_name'], unique=False)
    op.add_column('conversations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('conversations_creator_id_fkey'), 'conversations', 'users', ['creator_id'], ['id'])
    op.add_column('conversation_participants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_connections_pair'), 'connections', ['requester_id', 'addressee_id'], postgresql_nulls_not_distinct=False)
    op.create_table('workout_plans_users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trainee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trainer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_trainer_provided', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plans_users_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], name=op.f('workout_plans_users_trainee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('workout_plans_users_trainer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_plans_users_pkey'))
    )
    # ### end Alembic commands ###
