"""Connection Type for socials

Revision ID: 75835e25b777
Revises: 22630b7a2cf4
Create Date: 2026-04-24 13:10:15.491911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75835e25b777'
down_revision: Union[str, Sequence[str], None] = '22630b7a2cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
        # Create the enum type FIRST
    connectiontype = sa.Enum('friend', 'trainership', name='connectiontype')
    connectiontype.create(op.get_bind())  # <-- this line was missing

    op.add_column('connections', sa.Column('type', sa.Enum('friend', 'trainership', name='connectiontype'), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'type')
    # ### end Alembic commands ###
