"""refactored workout schemas

Revision ID: 7b004c282190
Revises: ba2d4ceaff47
Create Date: 2026-04-12 21:03:50.131141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b004c282190'
down_revision: Union[str, Sequence[str], None] = 'ba2d4ceaff47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_exer_tags')
    op.drop_table('workout_plan_plan_tags')
    op.drop_table('workout_plan_tags')
    op.drop_table('tags')
    op.drop_table('workout_plan_workouts')
    op.drop_table('workout_exercises')
    op.add_column('exercises', sa.Column('instruction', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('is_equipment_needed', sa.Boolean(), nullable=False))
    op.add_column('exercises', sa.Column('video_url', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'muscle_group')
    op.add_column('workout_plans', sa.Column('days_per_week', sa.Integer(), nullable=True))
    op.add_column('workout_plans', sa.Column('is_trainer_provided', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'is_trainer_provided')
    op.drop_column('workout_plans', 'days_per_week')
    op.add_column('exercises', sa.Column('muscle_group', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('equipment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'image_url')
    op.drop_column('exercises', 'video_url')
    op.drop_column('exercises', 'is_equipment_needed')
    op.drop_column('exercises', 'instruction')
    op.create_table('workout_exercises',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('workout_exercises_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('workout_exercises_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_exercises_pkey'))
    )
    op.create_table('workout_plan_workouts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plan_workouts_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('workout_plan_workouts_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_plan_workouts_pkey'))
    )
    op.create_table('tags',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('name', name=op.f('tags_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('workout_plan_tags',
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plan_tags_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('workout_plan_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'tag_id', name=op.f('workout_plan_tags_pkey'))
    )
    op.create_table('workout_plan_plan_tags',
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_plan_plan_tags_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['plan_tags.id'], name=op.f('workout_plan_plan_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'tag_id', name=op.f('workout_plan_plan_tags_pkey'))
    )
    op.create_table('exercise_exer_tags',
    sa.Column('exercise_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercise_exer_tags_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['exer_tags.id'], name=op.f('exercise_exer_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'tag_id', name=op.f('exercise_exer_tags_pkey'))
    )
    # ### end Alembic commands ###
