"""cascade all field

Revision ID: 8963badc8db2
Revises: 5a06acdbf20c
Create Date: 2026-04-22 10:46:13.000730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8963badc8db2'
down_revision: Union[str, Sequence[str], None] = '5a06acdbf20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_logs_user_id_fkey'), 'event_logs', type_='foreignkey')
    op.create_foreign_key(None, 'event_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('trainer_info_user_id_fkey'), 'trainer_info', type_='foreignkey')
    op.create_foreign_key(None, 'trainer_info', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_limitations_user_id_fkey'), 'user_limitations', type_='foreignkey')
    op.create_foreign_key(None, 'user_limitations', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_supplements_user_id_fkey'), 'user_supplements', type_='foreignkey')
    op.create_foreign_key(None, 'user_supplements', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('weight_loss_progress_user_id_fkey'), 'weight_loss_progress', type_='foreignkey')
    op.create_foreign_key(None, 'weight_loss_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weight_loss_progress', type_='foreignkey')
    op.create_foreign_key(op.f('weight_loss_progress_user_id_fkey'), 'weight_loss_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_supplements', type_='foreignkey')
    op.create_foreign_key(op.f('user_supplements_user_id_fkey'), 'user_supplements', 'user_profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_limitations', type_='foreignkey')
    op.create_foreign_key(op.f('user_limitations_user_id_fkey'), 'user_limitations', 'user_profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'trainer_info', type_='foreignkey')
    op.create_foreign_key(op.f('trainer_info_user_id_fkey'), 'trainer_info', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'event_logs', type_='foreignkey')
    op.create_foreign_key(op.f('event_logs_user_id_fkey'), 'event_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
