"""workout plans users association table

Revision ID: 896fa1e49bcf
Revises: 3f84a2f16673
Create Date: 2026-04-17 14:17:21.453425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896fa1e49bcf'
down_revision: Union[str, Sequence[str], None] = '3f84a2f16673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'is_trainer_provided')
    op.add_column('workout_plans_users', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('workout_plans_users', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('workout_plans_users', 'duration_weeks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans_users', sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout_plans_users', 'end_date')
    op.drop_column('workout_plans_users', 'start_date')
    op.add_column('workout_plans', sa.Column('is_trainer_provided', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
