"""new fields in workout plans

Revision ID: a63a1f92f371
Revises: f813e9a470bc
Create Date: 2026-04-15 10:44:48.755351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63a1f92f371'
down_revision: Union[str, Sequence[str], None] = 'f813e9a470bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serving_units', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('workout_plans', sa.Column('is_preset', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workout_plans', sa.Column('is_equipment_needed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workout_plans', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_constraint(op.f('workout_plans_assigned_to_fkey'), 'workout_plans', type_='foreignkey')
    op.drop_column('workout_plans', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('workout_plans_assigned_to_fkey'), 'workout_plans', 'users', ['assigned_to'], ['id'])
    op.drop_column('workout_plans', 'image_url')
    op.drop_column('workout_plans', 'is_equipment_needed')
    op.drop_column('workout_plans', 'is_preset')
    op.alter_column('serving_units', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
