"""is_active set to false default again, onboarding purposes

Revision ID: aa1dba5d87bd
Revises: 918f83d4e583
Create Date: 2026-04-18 12:00:34.638598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1dba5d87bd'
down_revision: Union[str, Sequence[str], None] = '918f83d4e583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
