"""exercise fields by reps and duration moved

Revision ID: b74e7b55146b
Revises: 356fe8be44a0
Create Date: 2026-04-18 13:13:27.011521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e7b55146b'
down_revision: Union[str, Sequence[str], None] = '356fe8be44a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_by_reps', sa.Boolean(), nullable=True))
    op.add_column('exercises', sa.Column('is_by_duration', sa.Boolean(), nullable=True))
    op.drop_column('exercises_workouts', 'is_by_reps')
    op.drop_column('exercises_workouts', 'is_by_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_workouts', sa.Column('is_by_duration', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exercises_workouts', sa.Column('is_by_reps', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'is_by_duration')
    op.drop_column('exercises', 'is_by_reps')
    # ### end Alembic commands ###
