"""macro integers

Revision ID: b82c00e7f9c2
Revises: 63dfdd844ec4
Create Date: 2026-05-09 00:01:15.844088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82c00e7f9c2'
down_revision: Union[str, Sequence[str], None] = '63dfdd844ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_onboarding', sa.Column('macro_protein_pct', sa.Integer(), nullable=True))
    op.add_column('user_onboarding', sa.Column('macro_carb_pct', sa.Integer(), nullable=True))
    op.add_column('user_onboarding', sa.Column('macro_fat_pct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_onboarding', 'macro_fat_pct')
    op.drop_column('user_onboarding', 'macro_carb_pct')
    op.drop_column('user_onboarding', 'macro_protein_pct')
    # ### end Alembic commands ###
