"""messages schema

Revision ID: b950be9aa291
Revises: 4b9b39582f02
Create Date: 2026-02-11 17:15:13.486087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b950be9aa291'
down_revision: Union[str, Sequence[str], None] = '4b9b39582f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_loss_progress', sa.Column('base_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weight_loss_progress', 'base_weight')
    # ### end Alembic commands ###
