"""add_is_active_to_users

Revision ID: ba2d4ceaff47
Revises: 7c91733271fd
Create Date: 2026-04-11 20:07:11.443633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2d4ceaff47'
down_revision: Union[str, Sequence[str], None] = '7c91733271fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows don't violate the constraint
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
