"""avatar_url

Revision ID: c5bb17f34f83
Revises: 09d2ee58aee0
Create Date: 2026-04-27 09:26:44.581454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bb17f34f83'
down_revision: Union[str, Sequence[str], None] = '09d2ee58aee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_url')
    # ### end Alembic commands ###
