"""cascade all social fields

Revision ID: d99c70948d8c
Revises: 8963badc8db2
Create Date: 2026-04-22 10:48:29.182754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99c70948d8c'
down_revision: Union[str, Sequence[str], None] = '8963badc8db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connections_requester_id_fkey'), 'connections', type_='foreignkey')
    op.drop_constraint(op.f('connections_addressee_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'users', ['addressee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversations_last_message_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_creator_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_reply_to_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_reply_to_id_fkey'), 'messages', 'messages', ['reply_to_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_creator_id_fkey'), 'conversations', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('conversations_last_message_id_fkey'), 'conversations', 'messages', ['last_message_id'], ['id'])
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_addressee_id_fkey'), 'connections', 'users', ['addressee_id'], ['id'])
    op.create_foreign_key(op.f('connections_requester_id_fkey'), 'connections', 'users', ['requester_id'], ['id'])
    # ### end Alembic commands ###
