"""workout stats and logs tables

Revision ID: e4aada73cbcd
Revises: 5fe6beeaa8a4
Create Date: 2026-04-22 08:52:06.808564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4aada73cbcd'
down_revision: Union[str, Sequence[str], None] = '5fe6beeaa8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_info', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'trainer_info', ['user_id'])
    op.create_foreign_key(None, 'trainer_info', 'users', ['user_id'], ['id'])
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'height',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_profiles', 'weight',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint(None, 'trainer_info', type_='foreignkey')
    op.drop_constraint(None, 'trainer_info', type_='unique')
    op.drop_column('trainer_info', 'user_id')
    # ### end Alembic commands ###
