"""workout video url

Revision ID: ffc55af2be47
Revises: 15cdf8090f93
Create Date: 2026-04-11 17:16:42.801382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc55af2be47'
down_revision: Union[str, Sequence[str], None] = '15cdf8090f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The following tables are being dropped, but they might not exist if a
    # previous migration already removed them. We'll comment them out to
    # prevent errors if they are already gone.
    # op.drop_constraint('meal_plan_items_meal_id_fkey', 'meal_plan_items', type_='foreignkey')
    # op.drop_index(op.f('ix_meals_name'), table_name='meals')
    # op.drop_table('meals')
    # op.drop_index(op.f('ix_meal_plans_date'), table_name='meal_plans')
    # op.drop_table('meal_plans')
    # op.drop_table('meal_plan_items')
    op.add_column('workout_plans', sa.Column('video_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'video_url')
    op.create_table('meal_plan_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_type', postgresql.ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'evening_snack', name='mealtype'), autoincrement=False, nullable=False),
    sa.Column('servings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('meal_plan_items_meal_id_fkey')),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('meal_plan_items_meal_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_plan_items_pkey'))
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meal_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_plans_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_meal_plans_user_id_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_meal_plans_date'), 'meal_plans', ['date'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', 'drink', 'dessert', 'other', name='mealcategory'), autoincrement=False, nullable=False),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('serving_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('meals_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meals_pkey'))
    )
    op.create_index(op.f('ix_meals_name'), 'meals', ['name'], unique=False)
    # ### end Alembic commands ###
